---
title: "Untitled"
author: "Ormo"
date: "5/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, 
               rethinking,
               zoo,
               naniar,
               lme4)

theme_set(theme_minimal())

x = seq(0, 10, by = 1)
y =  1 - 1/2^(0.5*x)
  
data.frame(x , y) %>% plot()

```

```{r}
create.agent <- function(input) {
  income = sample(10000:100000, 1)
  set_level =  rbeta(1, 5, 5)
  circumstance = rbeta(1, 5, 5)
  
  agent <- data.frame(
    materialism = sample(1:1e6,1)/1e6, # fixed materialism values
    income = income, # fixed income randomly assigned
    wealth = income * 3, # wealth at round 0
    consumption = 0, # consumption at round 0
    pp = 0, # personal property at round 0
    swb = NA,
    AL_c = 0,
    ID = NA,
    set_level = set_level, # unchanging factor from genetics etc.
    circumstance =  circumstance, # largely unchanged circumstances and demographic factor
    round = 1,
    swb_c = NA,
    ad = 0,
    n_prods = 1000,
    si = NA,
    swb5 = NA,
    pp5 = NA,
    w5 = NA,
    AL_swb = 0,
    swb_AL = NA,
    ad_swb = NA
  )
}

randomPairs <- function(list) {
  mix <- sample(list, length(list) / 2)
  match <- sample(list[-mix])
  return(data.frame(mix, match))
}

```


```{r simulating rounds}
rounds = 2:101
n_agents = 20
br_c = 9000
ad_xrate = 1
lr = 0.05
ad_factor = 0.5
dynamic_consumption = 0.01

compare = 10

world <- lapply(rep(1:n_agents, 1), create.agent)

# i = 2
# j = 1

for(i in rounds){
  for(j in 1:n_agents){
    agent <- world[[j]]
    n_prods = agent$n_prods[i-1]
  
    ID <- j
    m = agent$materialism[i-1] # constant materialism level
    income = agent$income[1] # constant income level
    w = agent$wealth[i - 1] # wealth from previous round
    
    disposible_w = w + income - br_c
    
    ## influence of consumption on SWB using AL theory
    c = rbinom(1, 1, m) * (# chance that an agent consume determined by materialism
      disposible_w * rbeta(1, 10 * m, 10 * (1 - m))) # proportion of wealth spent determined by materialism
    w = disposible_w - c # wealth after consumption
    n_prods = ifelse(c == 0, n_prods, n_prods + 1) # market diversity expanding as a response to products being consumed
    pp = ifelse(c == 0, 0, sample(1:n_prods, 1)) # What products does an agent have
    
    AL_c = sum(agent$consumption / sort((agent$round + 1), decreasing = T)) + c # AL at round i
    AL_c_lack = agent$AL_c[i - 1] # AL at round i - 1
    swb_c = ifelse(AL_c_lack + AL_c == 0, 
                   AL_c - AL_c_lack, 
                   (AL_c - AL_c_lack)/(mean(c(AL_c, AL_c_lack), rm.na = T))) # Relative AL
    
    ## influence of ad exposure on SWB
    n_ads = rpois(1, ad_xrate)
    
    max_mat_infl = rbeta(1, 10 * m, 10 * (1 - m)) # max influence of materialistic concepts on SWB
    ad_con_split = rbeta(1, 10, 10) # the split influence of advertisement and consumption
    
    infl_ad_pct <- 1 - 0.5^(0.5*n_ads)
    
    if(n_ads == 0){
      ad = 0
      
      ad_swb = 0
    } else{
      ad = sample(1:n_prods, n_ads) # What ads does an agent see?
      
      ad_swb = ifelse(ad %in% agent$pp, 1, -1) * m * ad_factor # does the agent have the object advertised for or not?
      
      ad_swb = sum(ad_swb)
    }
    
    swb = 0.5 * agent$set_level[1] + # set level happiness
      0.1 * agent$circumstance[1] + # set level circumstances - varying?
      0.4 * max_mat_infl * ad_con_split * 1 / (1 + exp(- swb_c)) + # influence of consumption on SWB
      0.4 * max_mat_infl * (1 - ad_con_split) * infl_ad_pct * 1 / (1 + exp(- ad_swb)) +
      0.4 * ((1 - max_mat_infl) + max_mat_infl * (1 - ad_con_split) * (1 - infl_ad_pct)) * rbeta(1, 50, 50) # random factor aka life
    
    
    round = i
    
    agent[i,] <- c(
      m,
      income,
      w,
      c,
      pp,
      swb,
      AL_c,
      ID,
      agent$set_level[1],
      agent$circumstance[1],
      round,
      swb_c,
      ad = 0,
      n_prods,
      si = 0,
      swb5 = 0,
      pp5 = 0,
      w5 = 0,
      AL_swb,
      swb_AL,
      ad_swb
    )
    
    
    agent$ad[i] <- paste(ad, collapse = ',')
    
    if(i <= (compare + 1)){
      agent$swb5[i] = sum(agent$swb, na.rm = T)/(i-1)
      agent$pp5[i] = sum(ifelse(agent$pp == 0, 0, 1), na.rm = T)/(i-1)
      agent$w5[i] = sum(agent$wealth, na.rm = T)/(i-1)
    }
    if(i > (compare + 1)) {
      agent$swb5[i] = sum(agent$swb[(i-(compare-1)):i], na.rm = T)/compare
      agent$pp5[i] = sum(ifelse(agent$pp[(i-(compare-1)):i] == 0, 0, 1), na.rm = T)/compare
      agent$w5[i] = sum(agent$wealth[((compare-1)):i], na.rm = T)/compare
    }
    
    AL_swb = sum(agent$swb / sort((agent$round + 1), decreasing = T), na.rm = T) + agent$swb[i] # AL at round i
    AL_swb_lack = agent$AL_swb[i - 1] # AL at round i - 1
    swb_AL = ifelse(AL_swb_lack + AL_swb == 0,
                    AL_swb_lack + AL_sw,
                    (AL_swb - AL_swb_lack)/mean(c(AL_swb, AL_swb_lack), rm.na = T)) # Relative AL

    
    agent$materialism[i] = ifelse(c == 0, 
                                  m - m * inv_logit(swb_AL)/100, 
                                  m + (1 - m) * inv_logit(swb_AL)/100)
    
    world[[j]] <- agent
  }
  
  MI6 <- randomPairs(1:length(world)) # defining agent meeting
  
  ## social interaction
  if ((i - 1) %% compare == 0) {
    for (k in 1:(n_agents / 2)) {
      meeting <- MI6[k, ]
      agent1 <- world[[meeting$mix]]
      agent2 <- world[[meeting$match]]
      
      if (agent1$pp5[i] + agent2$pp5[i] == 0) {
        perc1 <- 
          (1 - agent1$materialism[i]) * (agent1$swb5[i] - agent2$swb5[i]) +
          agent1$materialism[i] *
          (0.5 * ((agent1$w5[i] - agent2$w5[i]) / mean(c(agent1$w5[i], agent2$w5[i]), rm.na = T)) +
             0.5 * 1)
        
        perc2 <-
          (1 - agent2$materialism[i]) * (agent2$swb5[i] - agent1$swb5[i]) +
          agent2$materialism[i] *
          (0.5 * ((agent2$w5[i] - agent1$w5[i]) / mean(c(agent2$w5[i], agent1$w5[i]), rm.na = T)) +
             0.5 * 1)
        
      } else{
        perc1 <-
          (1 - agent1$materialism[i]) * (agent1$swb5[i] - agent2$swb5[i]) +
          agent1$materialism[i] *
          (0.5 * ((agent1$w5[i] - agent2$w5[i]) / mean(c(agent1$w5[i], agent2$w5[i]), rm.na = T)) +
             0.5 * ((agent1$pp5[i] - agent2$pp5[i]) / mean(c(agent1$pp5[i], agent2$pp5[i]), rm.na = T)
             ))
        
        perc2 <-
          (1 - agent2$materialism[i]) * (agent2$swb5[i] - agent1$swb5[i]) +
          agent2$materialism[i] *
          (0.5 * ((agent2$w5[i] - agent1$w5[i]) / mean(c(agent2$w5[i], agent1$w5[i]), rm.na = T)) +
             0.5 * ((agent2$pp5[i] - agent1$pp5[i]) / mean(c(agent2$pp5[i], agent1$pp5[i]), rm.na = T)
             ))
        
      }
      
      m_a1 <- ifelse(
        perc1 < -0.05 & perc1 > -0.5,
        agent1$materialism[i] + (agent2$materialism[i] - agent1$materialism[i]) * lr,
        agent1$materialism[i]
      )
      
      m_a2 <- ifelse(
        perc2 < -0.05 & perc2 > -0.5,
        agent2$materialism[i] + (agent1$materialism[i] - agent2$materialism[i]) * lr,
        agent2$materialism[i]
      )
      
      
      agent1$materialism[i] <- m_a1
      agent2$materialism[i] <- m_a2
      
      agent1$si[i] <- perc1
      agent2$si[i] <- perc2
      
      world[[meeting$mix]] <- agent1
      world[[meeting$match]] <- agent2
      
    }
  }
  if (i %% 100 == 0){print(i)}
}

```


```{r data formatting}
d <- data.frame(
    materialism = NA,
    income = NA, 
    wealth = NA, 
    consumption = NA, 
    pp = NA,
    swb = NA, 
    AL_c = NA,
    ID = NA,
    set_level = NA,
    circumstance = NA,
    round = NA,
    swb_c = NA,
    ad = NA,
    n_prods = NA,
    si = NA,
    swb5 = NA,
    pp5 = NA,
    w5 = NA,
    AL_swb = NA,
    swb_AL = NA,
    ad_swb = NA
)

for(i in 1:length(world)){
  d = rbind(d, world[[i]][rounds,])
}

d <- d %>% 
  na.omit() %>% 
  mutate(ID = as.factor(ID),
         round = round - 1)

```

```{r}
set.seed(47)

d %>% filter(ID %in% sample(1:n_agents, 5)) %>% 
  ggplot(aes(x = round, y = swb, color = ID)) +
  geom_line()

set.seed(47)

d %>% filter(ID %in% sample(1:n_agents, 5)) %>% 
  ggplot(aes(x = round, y = swb5, color = ID)) +
  geom_line()

d %>% filter(ID == 5) %>% 
  ggplot(aes(x = round)) +
  geom_line(aes(y = swb), color = 'firebrick') +
  geom_line(aes(y = swb5), color = 'royalblue')

d %>% filter(ID == 5) %>% 
  ggplot(aes(x = round)) +
  geom_line(aes(y = materialism), color = 'firebrick') +
  geom_line(aes(y = swb5), color = 'royalblue')

d %>% filter(ID == 1:5) %>% 
  ggplot(aes(x = round)) +
  geom_line(aes(y = materialism - swb5, color = ID)) 

```

```{r control graphs materialism}
d %>% ggplot(aes(x = round, y = materialism, color = ID)) +
  geom_line()

d %>% ggplot(aes(x = materialism, 
                 y = swb - 0.5 * set_level - 0.1 * circumstance)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, 
                 y = swb - 0.5 * set_level - 0.1 * circumstance,
                 color = ID)) +
  geom_point(alpha = 0.5, shape = 1) 

d %>% ggplot(aes(x = materialism, 
                 y = swb5 - 0.5 * set_level - 0.1 * circumstance)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, 
                 y = swb5 - 0.5 * set_level - 0.1 * circumstance,
                 color = ID)) +
  geom_point(alpha = 0.2, shape = 1)

d %>% ggplot(aes(x = materialism, y = swb)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, y = swb5)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, 
                 y = swb5,
                 color = ID)) +
  geom_point(alpha = 0.2, shape = 1) 
```


```{r control graphs SWB}
d %>% ggplot(aes(x = round, 
                 y = swb, 
                 color = ID)) +
  geom_line(alpha = 0.8) 

d %>% ggplot(aes(x = round, 
                 y = swb5, 
                 color = ID)) +
  geom_line(alpha = 0.8)

d %>% ggplot(aes(x = w5, 
                 y = swb5,
                 color = ID)) +
  geom_point(alpha = 0.2, 
             shape = 1)

d %>% ggplot(aes(x = log(w5), 
                 y = swb5 - 0.5 * set_level - 0.1 * circumstance,
                 color = ID)) +
  geom_point(alpha = 0.4, 
             shape = 1)

d %>% ggplot(aes(x = round, 
                 y = inv_logit( ad_swb), 
                 color = ID)) +
  geom_line(alpha = 0.8) 

```


```{r control graphs}
d %>% ggplot(aes(x = round, y = si, color = ID)) +
  geom_line()

d %>% ggplot(aes(x = round, 
                 y = inv_logit(swb_AL)/10, 
                 color = ID)) +
  geom_line(alpha = 0.8)

d %>% ggplot(aes(x = round, 
                 y = AL_c, 
                 color = ID)) +
  geom_line(alpha = 0.8) 
```

```{r}
d <- d %>% group_by(ID) %>% mutate(m_materialism = mean(materialism)) %>% ungroup()

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = (swb - 0.5 * set_level - 0.1 * circumstance)/0.4,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = (swb5 - 0.5 * set_level - 0.1 * circumstance)/0.4,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = swb,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = swb5,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

```




```{r correlation tests}

cor.test(d$materialism, d$swb - 0.4 * d$set_level - 0.1 * d$circumstance)

cor.test(d$wealth, d$swb - 0.4 * d$set_level - 0.1 * d$circumstance)

cor.test(d$materialism, d$round)

cor.test(d$swb, d$round)

cor.test(d$swb5, d$round)


```

```{r}
m1 <- lmer(data = d, swb ~ materialism + (1|ID))

m2 <- lmer(data = d, 
           swb5 ~ materialism + set_level + circumstance + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m3 <- lmer(data = d, 
           swb ~ materialism + scale(wealth) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m4 <- lmer(data = d, 
           swb ~ materialism + (1|ID) + (1|income),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m5 <- lmer(data = d, 
           swb ~ materialism + scale(income) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m6 <- lmer(data = d, 
           swb ~ materialism*scale(wealth) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m7 <- lmer(data = d, 
           swb ~ materialism*scale(income) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m8 <- lmer(data = d, 
           swb ~ materialism*scale(income)*scale(wealth) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m9 <- lmer(data = d, 
           swb5 ~ materialism + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

lm(data = d, materialism ~ scale(round))

m1
m2 # swb5
m3
m4
m5
m6
m7
m8
summary(m9)

```












