---
title: "Untitled"
author: "Ormo"
date: "5/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,
               zoo,
               naniar)

```

```{r}
create.agent <- function(input) {
  income = sample(10000:100000, 1) # income is determined by a random sample from 10000 to 100000
  set_level =  rbeta(1, 5, 5) # set level SWB - or the SWB determined by genetics randomly sampled from beta distribution
  circumstance = rbeta(1, 5, 5) # the SWB determined by circumstances randomly sampled from beta distribution
  materialism = sample(1:1e6,1)/1e6 # start level materialism sampled from a uniform distribution
  
  ## in order for the simulation to be smooth all the way through 5 rounds are simulated with a minimum level of interaction between the variables
  c = replicate(5, rbinom(1, 1, materialism))  # binary variable, consume or not with probability = materialism level
  n_prods = 1000 # number of product in the environment at round 0
  pp = replicate(5, sample(1:n_prods, 1)) * c # product added to pp if c = 1
  spending = c * rbeta(5, 10 * materialism, 10 * (1 - materialism)) # spending determined as a value from 0 to 1, determined by materialism level
  
  wealth = c() # place holder
  consumption <- c() # place holder
  AL_c_store = c() # place holder
  swb_c_store = c() # place holder
  
  swb_store = c() # place holder
  AL_swb_store = c() # place holder
  swb_AL_store = c() # place holder
  
  swb10 = c() # place holder
  w10 = c() # place holder
  pp10 = c() # place holder
  for(i in 1:5){
    w = wealth[i-1] # access wealth from last round
    con_i = ifelse(i == 1,
                   spending[i] * (income * 3 - br_c + income),
                   spending[i] * (w - br_c + income)) # size of consumption determined by wealth and materialism level
    consumption = c(consumption, con_i) # storing values
    
    w_i = ifelse(i == 1, 
                    income * 3 - br_c + income - con_i,
                    w - br_c + income - consumption[i]) # wealth determined by last rounds wealth and consumption this round
    wealth = c(wealth, w_i) # storing values
    
    AL_c = sum(consumption / sort( 1:i, decreasing = T)) # Adaptation level for consumption - size of stimuli divided by one over time since exposure
    AL_c_store = c(AL_c_store, AL_c) # storing values
    AL_c_lack = ifelse(i==1, 
                       0,
                       AL_c_store[i - 1]) # defining lacked adaptation level for consumption
    
    swb_c = ifelse(AL_c_lack + AL_c == 0, 
                   AL_c - AL_c_lack, 
                   (AL_c - AL_c_lack)/(mean(c(AL_c, AL_c_lack), rm.na = T))) # relative difference in AL from consumption
    swb_c_store = c(swb_c_store, swb_c) # storing values
    
    swb = 0.5 * set_level + 0.1 * circumstance + 0.4 * rbeta(1, 50, 50) # calculating SWB
    swb_store = c(swb_store, swb) # storing values
    
    n_prods_new = ifelse(c[i] == 0, n_prods, n_prods + 1) # adding a product to market if c==1
    n_prods = ifelse(i== 1,
                     n_prods_new,
                     c(n_prods, n_prods_new)) # storing values
    
    AL_swb = sum(swb / sort(1:i, decreasing = T), na.rm = T) # Adaptation level for swb - size of stimuli divided by one over time since exposure
    AL_swb_store = c(AL_swb_store, AL_swb) # storing values
    AL_swb_lack = ifelse(i==1, 
                       0,
                       swb_store[i - 1]) # defining lacked adaptation level for swb
    
    swb_AL = ifelse(AL_swb_lack + AL_swb == 0,
                    AL_swb_lack + AL_sw,
                    (AL_swb - AL_swb_lack)/mean(c(AL_swb, AL_swb_lack), rm.na = T)) # relative difference in AL from swb
    
    swb_AL_store = c(swb_AL_store, swb_AL) # storing values 
    
    swb10_i = ifelse(i==1,
                  swb,
                  mean(c(swb10, swb))) # calculating mean swb
    swb10 = c(swb10, swb10_i) # storing values
    
    w10_i = ifelse(i==1,
                wealth[i], 
                mean(c(w10, wealth[i]))) # calculating mean wealth
    w10 = c(w10, w10_i) # storing values
    
    pp10_i = mean(c[1:i]) # calculating mean product acquisition 
    pp10 = c(pp10, pp10_i) # storing values
  }
  
  # creating agent df from the variables specified above
  agent <- data.frame( 
    materialism = rep(materialism, 5), # stable materialism level for pre-simulation
    income = rep(income, 5), # stable income level
    wealth = wealth, # wealth defined above
    consumption = consumption, # consumption defined above
    pp = pp, # pp defined above
    swb = swb_store, # swb defined above
    AL_c = AL_c_store, # AL_c defined above
    ID = rep(NA, 5), # ID is assigned later
    set_level = rep(set_level, 5), # unchanging factor from genetics etc.
    circumstance =  rep(circumstance, 5), # largely unchanged circumstances and demographic factor
    round = 1:5, # the 5 presimulation rounds
    swb_c = swb_c_store, # swb_c defined above
    ad = rep(0,5), # no ads in pre-simulation
    n_prods = n_prods, # n_prods defined above
    si = rep(0, 5), # social interaction not available for pre-simulation
    swb10 = swb10, # swb10 defined above
    pp10 = pp10, # pp10 defined above
    w10 = w10, # w10 defined above
    AL_swb = AL_swb_store, # AL_swb defined above
    swb_AL = swb_AL_store, # swb_AL defined above
    ad_swb = rep(0,5), # no ads in pre-simulation
    n_ads = rep(0,5) # no ads in pre-simulation
  )
}

# defining function for randomly mixing list of agents for social interaction
randomPairs <- function(list) { # input = list of agent IDs
  mix <- sample(list, length(list) / 2) # sampling half of the agents
  match <- sample(list[-mix]) # mixing the other half
  return(data.frame(mix, match)) # connecting mix and match
}

```


```{r simulating rounds}
rounds = 200 + 5 # how many round of simulation + the 5 pre-simulation rounds
n_agents = 20 # how many agents
br_c = 9000 # what is the base rate consumption (cost of living)?
ad_xrate = 1 # what is the rate of ad exposure? (rate for poisson distribution)
lr = 0.005 # rate of assimilation between agents
ad_factor = 1 # influence of ads

compare = 10 # how often do agents engage in social interaction + length of avarage calculated (w10, swb10, and pp10) 

world <- lapply(rep(1:n_agents, 1), create.agent) # creating list of data frames (agents)

for(i in 6:rounds){
  for(j in 1:n_agents){
    agent <- world[[j]]
    n_prods = agent$n_prods[i-1]
  
    ID <- j
    m = agent$materialism[i-1] # constant materialism level
    income = agent$income[1] # constant income level
    w = agent$wealth[i - 1] # wealth from previous round
    
    disposible_w = w + income - br_c
    
    ## influence of consumption on SWB using AL theory
    c = rbinom(1, 1, m) * (# chance that an agent consume determined by materialism
      disposible_w * rbeta(1, 10 * m, 10 * (1 - m))) # proportion of wealth spent determined by materialism
    w = disposible_w - c # wealth after consumption
    n_prods = ifelse(c == 0, n_prods, n_prods + 1) # market diversity expanding as a response to products being consumed
    pp = ifelse(c == 0, 0, sample(1:n_prods, 1)) # What products does an agent have
    
    AL_c = sum(agent$consumption / sort((agent$round + 1), decreasing = T)) + c # AL at round i
    AL_c_lack = agent$AL_c[i - 1] # AL at round i - 1
    swb_c = ifelse(AL_c_lack + AL_c == 0, 
                   AL_c - AL_c_lack, 
                   (AL_c - AL_c_lack)/(mean(c(AL_c, AL_c_lack), rm.na = T))) # Relative AL
    
    ## influence of ad exposure on SWB
    n_ads = rpois(1, ad_xrate)
    
    max_mat_infl = rbeta(1, 10 * m, 10 * (1 - m)) # max influence of materialistic concepts on SWB
    ad_con_split = rbeta(1, 10, 10) # the split influence of advertisement and consumption
    
    infl_ad_pct <- 1 - 0.5^(0.5*n_ads)
    
    if(n_ads == 0){
      ad = 0
      
      ad_swb = 0
    } else{
      ad = sample(1:n_prods, n_ads) # What ads does an agent see?
      
      ad_swb = ifelse(ad %in% agent$pp, 1, -1) * m * ad_factor # does the agent have the object advertised for or not?
      
      ad_swb = sum(ad_swb)
    }
    
    swb = 0.5 * agent$set_level[1] + # set level happiness
      0.1 * agent$circumstance[1] + # set level circumstances - varying?
      0.4 * max_mat_infl * ad_con_split * 1 / (1 + exp(- swb_c)) + # influence of consumption on SWB
      0.4 * max_mat_infl * (1 - ad_con_split) * infl_ad_pct * 1 / (1 + exp(- ad_swb)) +
      0.4 * ((1 - max_mat_infl) + max_mat_infl * (1 - ad_con_split) * (1 - infl_ad_pct)) * rbeta(1, 50, 50) # random factor aka life
    
    
    round = i
    
    agent[i,] <- c(
      m,
      income,
      w,
      c,
      pp,
      swb,
      AL_c,
      ID,
      agent$set_level[1],
      agent$circumstance[1],
      round,
      swb_c,
      ad = 0,
      n_prods,
      si = 0,
      swb10 = 0,
      pp10 = 0,
      w10 = 0,
      AL_swb = 0,
      swb_AL = 0,
      ad_swb,
      n_ads
    )
    
    
    agent$ad[i] <- paste(ad, collapse = ',')
    
    if(i <= (compare + 1)){
      agent$swb10[i] = sum(agent$swb, na.rm = T)/(i)
      agent$pp10[i] = sum(ifelse(agent$pp == 0, 0, 1), na.rm = T)/(i)
      agent$w10[i] = sum(agent$wealth, na.rm = T)/(i)
    }
    if(i > (compare + 1)) {
      agent$swb10[i] = sum(agent$swb[(i-(compare-1)):i], na.rm = T)/compare
      agent$pp10[i] = sum(ifelse(agent$pp[(i-(compare-1)):i] == 0, 0, 1), na.rm = T)/compare
      agent$w10[i] = sum(agent$wealth[((compare-1)):i], na.rm = T)/compare
    }
    
    AL_swb = sum(agent$swb / sort((agent$round + 1), decreasing = T), na.rm = T) + agent$swb[i] # AL at round i
    AL_swb_lack = agent$AL_swb[i - 1] # AL at round i - 1
    swb_AL = ifelse(AL_swb_lack + AL_swb == 0,
                    AL_swb_lack + AL_sw,
                    (AL_swb - AL_swb_lack)/mean(c(AL_swb, AL_swb_lack), rm.na = T)) # Relative AL
    
    agent$AL_swb[i] <- AL_swb
    agent$swb_AL[i] <- swb_AL
    
    agent$materialism[i] = ifelse(c == 0, 
                                  m - m * inv_logit(swb_AL)/100, 
                                  m + (1 - m) * inv_logit(swb_AL)/100)
    
    world[[j]] <- agent
  }
  
  MI6 <- randomPairs(1:length(world)) # defining agent meeting
  
  ## social interaction
  if ((i - 1) %% compare == 0) {
    for (k in 1:(n_agents / 2)) {
      meeting <- MI6[k, ]
      agent1 <- world[[meeting$mix]]
      agent2 <- world[[meeting$match]]
      
      if (agent1$pp10[i] + agent2$pp10[i] == 0) {
        perc1 <- 
          (1 - agent1$materialism[i]) * (agent1$swb10[i] - agent2$swb10[i]) +
          agent1$materialism[i] *
          (0.5 * ((agent1$w10[i] - agent2$w10[i]) / mean(c(agent1$w10[i], agent2$w10[i]), rm.na = T)) +
             0.5 * 1)
        
        perc2 <-
          (1 - agent2$materialism[i]) * (agent2$swb10[i] - agent1$swb10[i]) +
          agent2$materialism[i] *
          (0.5 * ((agent2$w10[i] - agent1$w10[i]) / mean(c(agent2$w10[i], agent1$w10[i]), rm.na = T)) +
             0.5 * 1)
        
      } else{
        perc1 <-
          (1 - agent1$materialism[i]) * (agent1$swb10[i] - agent2$swb10[i]) +
          agent1$materialism[i] *
          (0.5 * ((agent1$w10[i] - agent2$w10[i]) / mean(c(agent1$w10[i], agent2$w10[i]), rm.na = T)) +
             0.5 * ((agent1$pp10[i] - agent2$pp10[i]) / mean(c(agent1$pp10[i], agent2$pp10[i]), rm.na = T)
             ))
        
        perc2 <-
          (1 - agent2$materialism[i]) * (agent2$swb10[i] - agent1$swb10[i]) +
          agent2$materialism[i] *
          (0.5 * ((agent2$w10[i] - agent1$w10[i]) / mean(c(agent2$w10[i], agent1$w10[i]), rm.na = T)) +
             0.5 * ((agent2$pp10[i] - agent1$pp10[i]) / mean(c(agent2$pp10[i], agent1$pp10[i]), rm.na = T)
             ))
        
      }
      
      m_a1 <- ifelse(
        perc1 < -0.05 & perc1 > -0.5,
        agent1$materialism[i] + (agent2$materialism[i] - agent1$materialism[i]) * lr,
        agent1$materialism[i]
      )
      
      m_a2 <- ifelse(
        perc2 < -0.05 & perc2 > -0.5,
        agent2$materialism[i] + (agent1$materialism[i] - agent2$materialism[i]) * lr,
        agent2$materialism[i]
      )
      
      
      agent1$materialism[i] <- m_a1
      agent2$materialism[i] <- m_a2
      
      agent1$si[i] <- perc1
      agent2$si[i] <- perc2
      
      world[[meeting$mix]] <- agent1
      world[[meeting$match]] <- agent2
      
    }
  }
  if (i %% 100 == 0){print(i)}
}

```


```{r data formatting}
d <- data.frame(
    materialism = NA,
    income = NA, 
    wealth = NA, 
    consumption = NA, 
    pp = NA,
    swb = NA, 
    AL_c = NA,
    ID = NA,
    set_level = NA,
    circumstance = NA,
    round = NA,
    swb_c = NA,
    ad = NA,
    n_prods = NA,
    si = NA,
    swb10 = NA,
    pp10 = NA,
    w10 = NA,
    AL_swb = NA,
    swb_AL = NA,
    ad_swb = NA,
    n_ads = NA
)

# for(i in 1:length(world)){
#   world[[i]]$ID = i
#   d = rbind(d, world[[i]])
# }

for(i in 1:length(world)){
  d = rbind(d, world[[i]][1:rounds,])
}

#d$ID <- na.locf0(d$ID, fromLast = T)

# d <- d %>% 
#   na.omit() %>% 
#   mutate(ID = as.factor(ID))

d <- d %>%
  na.omit() %>%
  mutate(ID = as.factor(ID),
         round = round - 5)

```

```{r}
set.seed(47)

d %>% filter(ID %in% sample(1:n_agents, 5)) %>% 
  ggplot(aes(x = round, y = swb, color = ID)) +
  geom_line()

set.seed(47)

d %>% filter(ID %in% sample(1:n_agents, 5)) %>% 
  ggplot(aes(x = round, y = swb10, color = ID)) +
  geom_line()

d %>% filter(ID == 5) %>% 
  ggplot(aes(x = round)) +
  geom_line(aes(y = swb), color = 'firebrick') +
  geom_line(aes(y = swb10), color = 'royalblue')

d %>% filter(ID == 5) %>% 
  ggplot(aes(x = round)) +
  geom_line(aes(y = materialism), color = 'firebrick') +
  geom_line(aes(y = swb10), color = 'royalblue')

d %>% filter(ID == 4 & round %% 6 == 0) %>% 
  mutate(lack_swb = c(NA, swb10[1:length(swb10)-1]),
                                 delta_swb = swb10 - lack_swb,
                                 lack_materialism = c(NA, materialism[1:length(materialism)-1]),
                                 delta_materialism = materialism - lack_materialism) %>% 

  ggplot(aes(x = round)) +
  geom_line(aes(y = delta_swb), color = 'royalblue') + 
  geom_line(aes(y = delta_materialism), color = 'firebrick')

d %>% filter(ID == 12 & round %% 2 == 0) %>% 
  mutate(lack_swb = c(NA, swb10[1:length(swb10)-1]),
                                 delta_swb = swb10 - lack_swb,
                                 lack_materialism = c(NA, materialism[1:length(materialism)-1]),
                                 delta_materialism = materialism - lack_materialism) %>% 

  ggplot(aes(x = round)) +
  geom_line(aes(y = delta_swb - delta_materialism), color = 'royalblue') 

```

```{r control graphs materialism}
d %>% ggplot(aes(x = round, y = materialism, color = ID)) +
  geom_line()

d %>% filter(round %in% c(1,500)) %>% ggplot(aes(x = round, y = materialism, color = ID)) +
  geom_line()


d %>% ggplot(aes(x = materialism, 
                 y = swb - 0.5 * set_level - 0.1 * circumstance)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, 
                 y = swb - 0.5 * set_level - 0.1 * circumstance,
                 color = ID)) +
  geom_point(alpha = 0.5, shape = 1) 

d %>% ggplot(aes(x = materialism, 
                 y = swb10 - 0.5 * set_level - 0.1 * circumstance)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, 
                 y = swb10 - 0.5 * set_level - 0.1 * circumstance,
                 color = ID)) +
  geom_point(alpha = 0.2, shape = 1)

d %>% ggplot(aes(x = materialism, y = swb)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, y = swb10)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, 
                 y = swb10,
                 color = ID)) +
  geom_point(alpha = 0.2, shape = 1) 

d %>% ggplot(aes(x = n_ads, 
                 y = swb10,
                 color = ID)) +
  geom_point(alpha = 0.2, shape = 1) 
```


```{r control graphs SWB}
d %>% ggplot(aes(x = round, 
                 y = swb, 
                 color = ID)) +
  geom_line(alpha = 0.8) 

d %>% ggplot(aes(x = round, 
                 y = swb10, 
                 color = ID)) +
  geom_line(alpha = 0.8)

d %>% ggplot(aes(x = w10, 
                 y = swb10,
                 color = ID)) +
  geom_point(alpha = 0.2, 
             shape = 1)

d %>% ggplot(aes(x = log(w10), 
                 y = swb10 - 0.5 * set_level - 0.1 * circumstance,
                 color = ID)) +
  geom_point(alpha = 0.4, 
             shape = 1)

d %>% ggplot(aes(x = log(w10), 
                 y = swb10 ,
                 color = ID)) +
  geom_point(alpha = 0.4, 
             shape = 1)

d %>% ggplot(aes(x = round, 
                 y = inv_logit(ad_swb), 
                 color = ID)) +
  geom_line(alpha = 0.8) 

```


```{r control graphs}
d %>% ggplot(aes(x = round, y = si, color = ID)) +
  geom_line()

d %>% ggplot(aes(x = round, 
                 y = swb_AL, 
                 color = ID)) +
  geom_line(alpha = 0.8)

d %>% ggplot(aes(x = round, 
                 y = AL_c, 
                 color = ID)) +
  geom_line(alpha = 0.8) 
```

```{r}
d <- d %>% group_by(ID) %>% mutate(m_materialism = mean(materialism)) %>% ungroup()

down_sample <- d %>% filter(as.numeric(ID) %% 2 == 0 & round %% 2 == 0)

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = (swb - 0.5 * set_level - 0.1 * circumstance)/0.4,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1, size = 3) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4) +
  ylab('Subjective Well-Being') +
  theme(text = element_text(size = 8),
        axis.text.x = element_text(angle = 0, hjust = 1)) 


d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = (swb10 - 0.5 * set_level - 0.1 * circumstance)/0.4,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1, size = 3) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)+
  ylab('Subjective Well-Being (10 round mean)') +
  theme(text = element_text(size = 8),
        axis.text.x = element_text(angle = 0, hjust = 1)) 
```

```{r}
reg <- function(x, y, col) abline(lm(y ~ x), col = col)

panel.lm <-
  function (x, y, col = par("col"), bg = NA, pch = par("pch"), 
            cex = 1, col.smooth = "red", span = 2 / 3, iter = 3, ...)  {
    points(x, y, pch = pch, col = col, bg = bg, cex = cex)
    ok <- is.finite(x) & is.finite(y)
    if (any(ok)) 
      reg(x[ok], y[ok], col.smooth)
  }

panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- cor(x, y)
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste0(prefix, txt)
  text(0.5, 0.5, txt, cex = 1.1, font = 4)
}

d$w5
```

```{r}
pairs( ~ materialism + swb + wealth + consumption + swb10 + w10, data = d,
  panel = panel.lm,
  cex = 1.5,
  pch = 19,
  col = adjustcolor(4, .4),
  cex.labels = 2,
  font.labels = 2,
  lower.panel = panel.cor
)


```




```{r}
d <- d %>% group_by(ID) %>% mutate(m_materialism = mean(materialism)) %>% ungroup()

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = (swb - 0.5 * set_level - 0.1 * circumstance)/0.4,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1, size = 3) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = (swb10 - 0.5 * set_level - 0.1 * circumstance)/0.4,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = swb,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

d %>% mutate(ID_n = as.numeric(ID),
             ID = fct_reorder(ID, m_materialism)) %>%
  ggplot(aes(x = ID, 
             y = swb10,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=median(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)

```




```{r correlation tests}

cor.test(d$materialism, d$swb - 0.4 * d$set_level - 0.1 * d$circumstance)

cor.test(d$wealth, d$swb - 0.4 * d$set_level - 0.1 * d$circumstance)

cor.test(d$materialism, d$round)

cor.test(d$swb, d$round)

cor.test(d$swb5, d$round)


```

```{r}
m1 <- lmer(data = d, swb ~ materialism + (1|ID))

m2 <- lmer(data = d, 
           swb5 ~ materialism + set_level + circumstance + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m3 <- lmer(data = d, 
           swb ~ materialism + scale(wealth) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m4 <- lmer(data = d, 
           swb ~ materialism + (1|ID) + (1|income),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m5 <- lmer(data = d, 
           swb ~ materialism + scale(income) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m6 <- lmer(data = d, 
           swb ~ materialism*scale(wealth) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m7 <- lmer(data = d, 
           swb ~ materialism*scale(income) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m8 <- lmer(data = d, 
           swb ~ materialism*scale(income)*scale(wealth) + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

m9 <- lmer(data = d, 
           swb5 ~ materialism + (1|ID),
           control = lmerControl(check.nobs.vs.nlev = "ignore", check.nobs.vs.nRE = "ignore"))

lm(data = d, materialism ~ scale(round))

m1
m2 # swb5
m3
m4
m5
m6
m7
m8
summary(m9)

```












