---
title: "Untitled"
author: "Ormo"
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, 
               rethinking,
               zoo,
               naniar)

theme_set(theme_minimal())

```

```{r creating agents}
create.agent <- function(input) {
  income = sample(10000:100000, 1)
  set_level = rbeta(1, 5, 5)
  circumstance = rbeta(1, 5, 5)
  
  agent <- data.frame(
    materialism = rbeta(1, 5, 5), # fixed materialism values
    income = income, # fixed income randomly assigned
    wealth = income * 3, # wealth at round 0
    consumption = 0, # consumption at round 0
    # social_consumption = consumption *
    # materistic_consumption = 1 - social_consumption
    pp = 0, # personal property at round 0
    swb = NA,
    AL = 0,
    ID = NA,
    set_level = set_level, # unchanging factor from genetics etc.
    circumstance =  circumstance, # largely unchanged circumstances and demographic factor
    round = 1,
    swb_c = NA,
    ad = 0
  )
}

```

```{r simulating rounds}
rounds = 2:401
n_agents = 50

br_c = 9000
ad_xrate = 1

world <- lapply(rep(1:n_agents, 1), create.agent)

for(j in 1:n_agents) {
  agent <- world[[j]]
  agent$ID[1] <- j
  n_prods = 1000
  for (i in rounds) {
    ID <- agent$ID[1]
    m = agent$materialism[1] # constant materialism level
    income = agent$income[1] # constant income level
    w = agent$wealth[i - 1] # wealth from previous round
    
    disposible_w = w + income - br_c
    
    ## influence of consumption on SWB using AL theory
    c = rbinom(1, 1, m) * (# chance that an agent consume determined by materialism
      disposible_w * rbeta(1, 10 * m, 10 * (1 - m))) # proportion of wealth spent determined by materialism
    w = disposible_w - c # wealth after consumption
    n_prods = ifelse(c == 0, n_prods, n_prods + 1) # market diversity expanding as a response to products being consumed
    
    AL = sum(agent$consumption / sort((agent$round + 1), decreasing = T)) + c # AL at round i
    AL_lack = agent$AL[i - 1] # AL at round i - 1
    swb_c = ifelse(AL_lack == 0, 0, (AL - AL_lack)/((AL + AL_lack)/2)) # Relative AL
    
    ## influence of ad exposure on SWB
    n_ads = rpois(1, ad_xrate)
    pp = ifelse(c == 0, 0, sample(1:n_prods, 1)) # What products does an agent have
    
    max_mat_infl = rbeta(1, 10 * m, 10 * (1 - m)) # max influence of materialistic concepts on SWB
    ad_con_split = rbeta(1,5,5) # the split influence of advertisement and consumption
    
    if(n_ads == 0){
      ad = 0
      
      swb = 0.5 * agent$set_level[1] + # set level happiness
        0.1 * agent$circumstance[1] + # set level circumstances - varying?
        0.4 * max_mat_infl * ad_con_split * 1 / (1 + exp(-swb_c)) + # influence of consumption on SWB
        0.4 * max_mat_infl * (1 - ad_con_split) * rbeta(1, 5, 5) + # no ads, no effect of ads thus random
        0.4 * (1 - max_mat_infl) * rbeta(1, 5, 5) # random factor - life's influence on SWB
    } else{
      ad = sample(1:n_prods, n_ads) # What ads does an agent see?
      infl_ad = ifelse(ad %in% agent$pp, 1, -1) * # does the agent have the object advertised for or not?
        0.2533 * m # by how much is the agent influenced? 
      infl_ad = sum(infl_ad)
      
      swb = 0.5 * agent$set_level[1] + # set level happiness
        0.1 * agent$circumstance[1] + # set level circumstances - varying?
        0.4 * max_mat_infl * ad_con_split * 1 / (1 + exp(-swb_c)) + # influence of consumption on SWB
        0.4 * max_mat_infl * (1 - ad_con_split) * 1 / (1 + exp(-infl_ad)) + # factor from advertisement
        0.4 * (1 - max_mat_infl) * rbeta(1, 5, 5) # random factor - life's influence on SWB
    }
    
    round = i
    
    agent[i,] <- c(
      m,
      income,
      w,
      c,
      pp,
      swb,
      AL,
      ID,
      agent$set_level[1],
      agent$circumstance[1],
      round,
      swb_c,
      ad = 0
    )
    
    agent$ad[i] <- paste(ad, collapse = ',')
    
  }
  world[[j]] <- agent
  #print(j)
}

```


```{r data formatting}
d <- data.frame(
    materialism = NA,
    income = NA, 
    wealth = NA, 
    consumption = NA, 
    pp = NA,
    swb = NA, 
    AL = NA,
    ID = NA,
    set_level = NA,
    circumstance = NA,
    round = NA,
    swb_c = NA,
    ad = NA
)

for(i in 1:length(world)){
  d = rbind(d, world[[i]][rounds,])
}

d <- d %>% 
  na.omit() %>% 
  mutate(ID = as.factor(ID),
         round = round - 1)
```

```{r}
d %>% filter(ID %in% sample(1:n_agents, 5)) %>% ggplot(aes(x = round, y = swb, color = ID)) +
  geom_line()

world[[7]] %>% ggplot(aes(x = round)) +
  geom_line(aes(y = consumption), color = 'firebrick') 


world[[7]] %>% ggplot(aes(x = round)) +
  geom_line(aes(y = swb), color = 'firebrick') +
  geom_line(aes(y = inv_logit(swb_c)))

rbind(
  filter(d, materialism == max(d$materialism)),
  filter(d, materialism == min(d$materialism))
) %>% ggplot(aes(x = round, color = ID)) +
  geom_line(aes(y = swb))


```

```{r plots}
d %>% ggplot(aes(x = wealth, y = swb, color = ID)) +
  geom_point(shape = 1, alpha = 0.7) +
  geom_smooth(method = 'lm') +
  xlim(0,1e5) +
  ylim(0,1)

d %>% ggplot(aes(x = round, y = wealth, color = ID)) +
  geom_line()

d %>% ggplot(aes(x = consumption, y = swb - 0.5 * set_level - 0.1 * circumstance, color = ID)) +
  geom_jitter(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = consumption, y = swb, color = ID)) +
  geom_jitter(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, y = swb - 0.5 * set_level - 0.1 * circumstance)) +
  geom_jitter(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = materialism, y = swb)) +
  geom_jitter(alpha = 0.3, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = round, y = AL, color = ID)) +
  geom_line(alpha = 0.7) + ylim(0, 1e6)

d %>% ggplot(aes(x = round, y = swb_c, color = ID)) +
  geom_line(alpha = 0.7)

d %>% ggplot(aes(x = round, y = inv_logit(swb_c), color = ID)) +
  geom_line(alpha = 0.7)

d %>% ggplot(aes(x = scale(income), y = swb - 0.5 * set_level - 0.1 * circumstance)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = scale(income), y = swb)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

d %>% ggplot(aes(x = round, y = swb)) +
  geom_point(alpha = 0.2, shape = 1) +
  geom_smooth(method = 'lm')

```
```{r}
d %>% mutate(ID = as.factor(ID),
             ID = fct_reorder(ID, materialism)) %>%
  ggplot(aes(x = ID, 
             y = swb,
             color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  geom_errorbar(aes(ymin =  0.5 * set_level + 0.1 * circumstance, 
                    ymax =  0.5 * set_level + 0.1 * circumstance + 0.4), 
                width = .2) +
  scale_color_gradient2(midpoint=mean(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") + 
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange", shape = 3)

d %>% mutate(ID = as.factor(ID),
             ID = fct_reorder(ID, materialism)) %>%
  ggplot(aes(x = ID, 
             y = (swb - 0.5 * set_level - 0.1 * circumstance)/0.4,
         color = materialism)) +
  geom_point(alpha = 0.5, shape = 1) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                 geom="point", color="orange",
               shape = 3) +
  scale_color_gradient2(midpoint=mean(d$materialism), 
                        low="royalblue", 
                        mid="black",
                        high="firebrick", 
                        space ="Lab") +
  geom_hline(yintercept = 0.5, lty = 2, alpha = 0.4)
  


```


```{r correlation tests}

cor.test(d$materialism, d$swb - 0.4 * d$set_level - 0.1 * d$circumstance)

cor.test(d$wealth, d$swb - 0.4 * d$set_level - 0.1 * d$circumstance)

cor.test(d$materialism, d$swb)

cor.test(d$wealth, d$swb)


```












```{r}
# i = 2
# j = 1
# 
# for(j in 1:length(world)) {
#   agent <- world[[j]]
#   agent$ID[1] <- j
#   for (i in rounds) {
#     i = i + 1
#     m = agent$materialism[1]
#     
#     disposible_w = agent$wealth[i-1] + agent$income[1] - br_c # Agent wealth before consumption
#     c = rbinom(1, 1, m) * ( # chance that an agent consume
#       disposible_w * rbeta(1, 10 * m, 10 * (1 - m)) # proportion of wealth spent determined by materialism
#     )
#     
#     w = disposible_w - c
#     
#     pp = ifelse(c == 0, 0, sample(1:n_ads, 1)) # personal property
#     
#     swb_consumption = 0 # placeholder variable
#     
#     
#     swb_consumption = sum(agent$consumption / sort((agent$round + 1), decreasing = T)) + c
#     
#     swb = 0.5 * agent$set_level[1] + # set level happiness
#       0.1 * agent$circumstance[1] + # c
#       0.4 * (swb_consumption/1000)/sqrt(1 + (swb_consumption/1000)^2) # consumption
#     
#     round = i - 1
#     
#     agent[i, ] <- c(m, 
#                     agent$income[1], 
#                     w, 
#                     c, 
#                     pp, 
#                     swb, 
#                     swb_consumption, 
#                     agent$ID[1], 
#                     agent$set_level[1], 
#                     agent$circumstance[1], 
#                     round)
#   }
#   world[[j]] <- agent
#   # print(j)
# }
```


